/* Judges as listed on dsh-hacks-v2.devpost.com and dsh-hacks-v1.devpost.com
   (organizer accounts left out). Photos in /public/judges/people. */
export type Judge = { name: string; title: string; img: string | null; v: "V1" | "V2" };

export const JUDGES: Judge[] = [
  { name: "Sunil Divvela", title: "Worldwide Senior Solutions Architect", img: "/judges/people/sunil-divvela.jpg", v: "V2" },
  { name: "Alina Olefirenko", title: "CTO", img: "/judges/people/alina-olefirenko.jpg", v: "V2" },
  { name: "Rajesh Kumar", title: "Principal Enterprise Architect | MuleSoft Ambassador | Axonis Edge AI Ambassador", img: "/judges/people/rajesh-kumar.jpg", v: "V2" },
  { name: "Sandeep Vattikuti", title: "Principal Engineer – Cloud, Data & DevSecOps Architecture, Texas Health and Human Services Commission (HHSC)", img: "/judges/people/sandeep-vattikuti.jpg", v: "V2" },
  { name: "Sourav Saha", title: "Assistant Vice President, Senior Software Engineer, U.S. Bank", img: "/judges/people/sourav-saha.jpg", v: "V2" },
  { name: "Aatish Kumar", title: "Founding Engineer, StyleFrame AI", img: "/judges/people/aatish-kumar.jpg", v: "V2" },
  { name: "Anudeep Bonagiri", title: "Co-Founder & CEO at Cruze", img: "/judges/people/anudeep-bonagiri.jpg", v: "V2" },
  { name: "Aishwarya Nair", title: "Senior Data Engineer", img: "/judges/people/aishwarya-nair.jpg", v: "V2" },
  { name: "Bhargav K Korrapati", title: "Sr. Software Engineer", img: "/judges/people/bhargav-k-korrapati.jpg", v: "V2" },
  { name: "Ratna Kumar Bonagiri", title: "Staff Software Engineer", img: "/judges/people/ratna-kumar-bonagiri.jpg", v: "V2" },
  { name: "Himanshu Pandey", title: "Senior Software Engineer", img: "/judges/people/himanshu-pandey.jpg", v: "V2" },
  { name: "Nandish Nanjappa", title: "Staff Software Engineer at Attentive Mobile", img: "/judges/people/nandish-nanjappa.jpg", v: "V2" },
  { name: "Ankur Bhatnagar", title: "Enterprise Integration & API Architect", img: "/judges/people/ankur-bhatnagar.jpg", v: "V2" },
  { name: "Omer Dogan", title: "CEO & Managing Director at Mono Apps", img: "/judges/people/omer-dogan.jpg", v: "V2" },
  { name: "Bhagath Siddi", title: "Senior Manager", img: "/judges/people/bhagath-siddi.jpg", v: "V2" },
  { name: "Pratik Gupta", title: "Senior Engineering Leader, Stripe", img: "/judges/people/pratik-gupta.jpg", v: "V2" },
  { name: "Sanjay Singh", title: "Staff Software Engineer", img: "/judges/people/sanjay-singh.jpg", v: "V2" },
  { name: "Subham Kumar", title: "Senior Software Engineer", img: "/judges/people/subham-kumar.jpg", v: "V2" },
  { name: "Dulra Amolegbe", title: "Co-founder / CEO", img: "/judges/people/dulra-amolegbe.jpg", v: "V2" },
  { name: "Akshay Talathi", title: "Vice President of Software Engineering at Goldman Sachs", img: "/judges/people/akshay-talathi.jpg", v: "V2" },
  { name: "Krishna Kuruvella", title: "Tech Lead/software engineer", img: "/judges/people/krishna-kuruvella.jpg", v: "V2" },
  { name: "Yeswant Kumar", title: "AI & Supply Chain Solution Architect", img: "/judges/people/yeswant-kumar.jpg", v: "V2" },
  { name: "Ravi Shanker Thadishetti", title: "Senior Software Engineer", img: "/judges/people/ravi-shanker-thadishetti.jpg", v: "V2" },
  { name: "Santiago Orozco", title: "Founding Engineer at Cubic (YC S25)", img: "/judges/people/santiago-orozco.jpg", v: "V2" },
  { name: "Yash Mundada", title: "Former Software Engineer at Meta, HubSpot, and Amazon", img: "/judges/people/yash-mundada.jpg", v: "V2" },
  { name: "Shreyans Lodha", title: "Former Columbia Business School and D. E. Shaw", img: "/judges/people/shreyans-lodha.jpg", v: "V2" },
  { name: "Lovleen Kaur", title: "Software Engineer, Cisco Systems", img: "/judges/people/lovleen-kaur.jpg", v: "V1" },
  { name: "Avaneesh Desai", title: "Senior Frontend Engineer, Highspot", img: "/judges/people/avaneesh-desai.jpg", v: "V1" },
  { name: "Sharan Babu ParamasivamMurugesan", title: "Senior Software Engineer, Microsoft", img: "/judges/people/sharan-babu-paramasivammurugesan.jpg", v: "V1" },
  { name: "Parth Rana", title: "Assistant Vice President, State Street", img: "/judges/people/parth-rana.jpg", v: "V1" },
  { name: "Suraj Devatha", title: "Senior Software Engineer", img: "/judges/people/suraj-devatha.jpg", v: "V1" },
  { name: "Danil Matrosov", title: "Founder & CEO, Octery", img: "/judges/people/danil-matrosov.jpg", v: "V1" },
  { name: "Aman Bakshi", title: "Senior Software Engineer, Apple", img: "/judges/people/aman-bakshi.jpg", v: "V1" },
  { name: "Gediminas Pažėra", title: "Healthcare AI Engineer (Oxford PhD)", img: "/judges/people/gediminas-pa-ra.jpg", v: "V1" },
  { name: "Bharat Khanna", title: "Senior Staff Backend and AI Systems Engineer, Achieve", img: "/judges/people/bharat-khanna.jpg", v: "V1" },
  { name: "Chandni Bhatia", title: "Vice President and Lead Quantitative Developer", img: "/judges/people/chandni-bhatia.jpg", v: "V1" },
  { name: "Preethi Bharathy", title: "Data Scientist", img: "/judges/people/preethi-bharathy.jpg", v: "V1" },
  { name: "Srinath Gopinath", title: "Reliability Engineer", img: "/judges/people/srinath-gopinath.jpg", v: "V1" },
  { name: "Jay-Jay Qian", title: "Member of Technical Staff (Data Science)", img: "/judges/people/jay-jay-qian.jpg", v: "V1" },
  { name: "Sai Joshitha Kathari", title: "Senior Site Reliability Engineer", img: "/judges/people/sai-joshitha-kathari.jpg", v: "V1" },
  { name: "Dishant Shahani", title: "Technical Lead", img: "/judges/people/dishant-shahani.jpg", v: "V1" },
  { name: "Prabu Deivendran", title: "Senior Technical Lead at HCL America, Inc", img: "/judges/people/prabu-deivendran.jpg", v: "V1" },
  { name: "Logeshwari Ramalingam", title: "Senior Software Engineer at PayPal", img: "/judges/people/logeshwari-ramalingam.jpg", v: "V1" },
  { name: "Venkata Krishna Bharadwaj Parasaram", title: "Senior Project Manager", img: "/judges/people/venkata-krishna-bharadwaj-parasaram.jpg", v: "V1" },
  { name: "Urvi Bhanushali", title: "Software Engineer at Meta", img: "/judges/people/urvi-bhanushali.jpg", v: "V1" },
  { name: "Ankita Agrawal", title: "Senior Member of Technical Staff", img: "/judges/people/ankita-agrawal.jpg", v: "V1" },
  { name: "Ansh Bilimoria", title: "Software Engineer at Meta", img: "/judges/people/ansh-bilimoria.jpg", v: "V1" },
  { name: "Mihir Shelar", title: "Senior Technical Program Manager at Amazon", img: "/judges/people/mihir-shelar.jpg", v: "V1" },
  { name: "Vaibhav Sharma", title: "Cloud Data Platform Engineer, Ford Credit", img: "/judges/people/vaibhav-sharma.jpg", v: "V1" },
  { name: "Pallavi Shrivastava", title: "Vice President Product Marketing at U.S. Bank", img: "/judges/people/pallavi-shrivastava.jpg", v: "V1" },
  { name: "Chirag Vinodkumar Pandey", title: "Software Engineer, Amazon Web Services", img: "/judges/people/chirag-vinodkumar-pandey.jpg", v: "V1" },
  { name: "Swarup Dongare", title: "Data Engineering Management and Governance Manager at Accenture", img: "/judges/people/swarup-dongare.jpg", v: "V1" },
  { name: "Maksym Strizhov", title: "Founder & Lead Systems Architect at VOID Systems", img: "/judges/people/maksym-strizhov.jpg", v: "V1" },
  { name: "Ken Chew", title: "Data Science/Machine Learning Lead", img: "/judges/people/ken-chew.jpg", v: "V1" },
  { name: "Atharv Chandratre", title: "Software Engineer, DoorDash", img: "/judges/people/atharv-chandratre.jpg", v: "V1" },
  { name: "Ravi Kiran Pagidi", title: "Senior Data Engineer (AI/ML/NLP)", img: "/judges/people/ravi-kiran-pagidi.jpg", v: "V1" },
  { name: "Alex Dainiak", title: "Developer", img: "/judges/people/alex-dainiak.jpg", v: "V1" },
  { name: "Ravi Teja", title: "Senior Site Reliability Engineer at Oracle America Inc", img: "/judges/people/ravi-teja.jpg", v: "V1" },
  { name: "Anusha Mukka", title: "Software Engineer", img: "/judges/people/anusha-mukka.jpg", v: "V1" },
  { name: "Harshavardhan Peddireddy", title: "Platform Architect at Meijer INC, Michigan, USA", img: "/judges/people/harshavardhan-peddireddy.jpg", v: "V1" },
  { name: "Ifeoma Eleweke", title: "DevOps Engineer", img: "/judges/people/ifeoma-eleweke.jpg", v: "V1" },
  { name: "Jim Markunas", title: "Senior Project Manager", img: "/judges/people/jim-markunas.jpg", v: "V1" },
  { name: "Dulra Amolegbe", title: "Cofounder/CEO, Carmel Labs", img: "/judges/people/dulra-amolegbe.jpg", v: "V1" },
  { name: "Bhavya Bommireddy", title: "Senior Software Engineer at Microsoft", img: "/judges/people/bhavya-bommireddy.jpg", v: "V1" },
  { name: "Puneet Bajaj", title: "Founding Engineer, BluePill AI", img: "/judges/people/puneet-bajaj.jpg", v: "V1" },
  { name: "Akshay Sharma", title: "Principal Data Engineer at Capital One", img: "/judges/people/akshay-sharma.jpg", v: "V1" },
  { name: "Karthik Karunanithi", title: "Solution Architect at IBM", img: "/judges/people/karthik-karunanithi.jpg", v: "V1" },
  { name: "Bedil Karimov", title: "Senior Systems Engineer", img: "/judges/people/bedil-karimov.jpg", v: "V1" },
  { name: "Xingpeng Xiao", title: "Software Engineering Manager", img: "/judges/people/xingpeng-xiao.jpg", v: "V1" },
  { name: "Prashant Krishnan V", title: "Machine Learning Data Scientist, Semantics at Apple", img: "/judges/people/prashant-krishnan-v.jpg", v: "V1" },
  { name: "Het Pathak", title: "Solutions Associate", img: "/judges/people/het-pathak.jpg", v: "V1" },
  { name: "Krishna Chaitanya Yarlagadda", title: "Director, Data Science & AI", img: "/judges/people/krishna-chaitanya-yarlagadda.jpg", v: "V1" },
  { name: "Gayathri Bollineni", title: "Lead SDET", img: "/judges/people/gayathri-bollineni.jpg", v: "V1" },
  { name: "Swapnil Nagar", title: "Senior Software Engineer, Agentic Platform @ Azure Functions", img: "/judges/people/swapnil-nagar.jpg", v: "V1" },
  { name: "Vaibhav Patel", title: "AI Engineer", img: "/judges/people/vaibhav-patel.jpg", v: "V1" },
  { name: "Roopam Choudhari", title: "Staff Product Manager at Walmart", img: "/judges/people/roopam-choudhari.jpg", v: "V1" },
  { name: "Volodymyr Lopukhovych", title: "Lead Software Engineer", img: "/judges/people/volodymyr-lopukhovych.jpg", v: "V1" },
  { name: "Ankur Bhatnagar", title: "Staff Software Engineer/Architect", img: "/judges/people/ankur-bhatnagar.jpg", v: "V1" },
  { name: "Ratna Kumar Bonagiri", title: "Senior Distributed Systems and Data Platform Architect", img: "/judges/people/ratna-kumar-bonagiri.jpg", v: "V1" },
  { name: "Eshaan Jain", title: "Lead Product Owner, Salesforce CPQ & Enterprise AI at T-Mobile", img: "/judges/people/eshaan-jain.jpg", v: "V1" },
  { name: "Maulik Bhatt", title: "Senior Software Development Engineer at Amazon Web Services (AWS)", img: "/judges/people/maulik-bhatt.jpg", v: "V1" },
  { name: "Varadharajan Chandran", title: "Engineering Manager and Software Architect, Vision Products Group, Apple", img: "/judges/people/varadharajan-chandran.jpg", v: "V1" },
  { name: "Sameena Begam Savukath Ali", title: "Principal Software Engineer, Liberty Mutual, USA", img: "/judges/people/sameena-begam-savukath-ali.jpg", v: "V1" },
  { name: "Karan Shah", title: "Product Manager", img: "/judges/people/karan-shah.jpg", v: "V1" },
  { name: "Ankit Srivastava", title: "Sr. Data Engineer", img: "/judges/people/ankit-srivastava.jpg", v: "V1" },
  { name: "Vasu Jain", title: "Salesforce Manager", img: "/judges/people/vasu-jain.jpg", v: "V1" },
  { name: "Andrei Shcherbinin", title: "Team Lead ML Engineer", img: "/judges/people/andrei-shcherbinin.jpg", v: "V1" },
  { name: "Jay Goradia", title: "Technical Account Manager – Amazon Web Services (AWS)", img: "/judges/people/jay-goradia.jpg", v: "V1" },
  { name: "Swarnamalya Mohan", title: "Senior Full Stack Developer AI/ML at FedEx", img: "/judges/people/swarnamalya-mohan.jpg", v: "V1" },
  { name: "Dmytro Zaharnytskyi", title: "Senior Software Engineer", img: "/judges/people/dmytro-zaharnytskyi.jpg", v: "V1" },
  { name: "Ratish Kumar Saravanan", title: "Solutions Engineer", img: "/judges/people/ratish-kumar-saravanan.jpg", v: "V1" },
  { name: "Mihir Soni", title: "Engineering Manager, Azure Comoute Microsoft", img: "/judges/people/mihir-soni.jpg", v: "V1" },
  { name: "Madhumitha Saravanan", title: "Software Engineer", img: "/judges/people/madhumitha-saravanan.jpg", v: "V1" },
  { name: "Artem Atamanchuk", title: "Senior DevOps Engineer at RubyPlay", img: "/judges/people/artem-atamanchuk.jpg", v: "V1" },
  { name: "Lokendra Panwar", title: "Senior Software Engineer, Amazon Web Services", img: "/judges/people/lokendra-panwar.jpg", v: "V1" },
  { name: "Reshmika Dhandapani", title: "Product Manager", img: "/judges/people/reshmika-dhandapani.jpg", v: "V1" },
  { name: "Hareesha Rameshappa", title: "Sr Technical Product Manager", img: "/judges/people/hareesha-rameshappa.jpg", v: "V1" },
  { name: "Suresh Kumar Palus", title: "Lead Software Engineer, Paramount", img: "/judges/people/suresh-kumar-palus.jpg", v: "V1" },
  { name: "Atul Khanna", title: "Enterprise Support Manager, Amazon Inc", img: "/judges/people/atul-khanna.jpg", v: "V1" },
  { name: "Upendra Jadon", title: "Solutions Architect @ DataMasque", img: "/judges/people/upendra-jadon.jpg", v: "V1" },
  { name: "Sarah Sonje", title: "Senior Member of Technical Staff at Oracle Databases", img: "/judges/people/sarah-sonje.jpg", v: "V1" },
  { name: "Sarvesh Gupta", title: "Consulting Member of Technical Staff at Oracle", img: "/judges/people/sarvesh-gupta.jpg", v: "V1" },
  { name: "Siyuan Feng", title: "Data Analyst at Corporation Service Company (CSC)", img: "/judges/people/siyuan-feng.jpg", v: "V1" },
  { name: "Japser Shi", title: "Founder & CEO, Bytey", img: "/judges/people/japser-shi.jpg", v: "V1" },
  { name: "Luzhuo Chen", title: "Co-founder & CTO, Bytey", img: "/judges/people/luzhuo-chen.jpg", v: "V1" },
];
